// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNUlJbX1DXD7pKjssyrwdFgP8kLLH_VjU',
    appId: '1:29681045164:web:45085e8c0d669a76bb5909',
    messagingSenderId: '29681045164',
    projectId: 'wesal-v2',
    authDomain: 'wesal-v2.firebaseapp.com',
    storageBucket: 'wesal-v2.firebasestorage.app',
    measurementId: 'G-SKGJH6MQKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEeFJ_TOQhctyRpvJ13WWrEQ6vD6xsEk4',
    appId: '1:29681045164:android:129d1ff9fa34bd02bb5909',
    messagingSenderId: '29681045164',
    projectId: 'wesal-v2',
    storageBucket: 'wesal-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsElODpEWaePSicgYUoJ_b9sFOODBSmeo',
    appId: '1:29681045164:ios:a282da5a12491237bb5909',
    messagingSenderId: '29681045164',
    projectId: 'wesal-v2',
    storageBucket: 'wesal-v2.firebasestorage.app',
    iosBundleId: 'com.example.wesalApplicationV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsElODpEWaePSicgYUoJ_b9sFOODBSmeo',
    appId: '1:29681045164:ios:a282da5a12491237bb5909',
    messagingSenderId: '29681045164',
    projectId: 'wesal-v2',
    storageBucket: 'wesal-v2.firebasestorage.app',
    iosBundleId: 'com.example.wesalApplicationV3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNUlJbX1DXD7pKjssyrwdFgP8kLLH_VjU',
    appId: '1:29681045164:web:e227331119e07539bb5909',
    messagingSenderId: '29681045164',
    projectId: 'wesal-v2',
    authDomain: 'wesal-v2.firebaseapp.com',
    storageBucket: 'wesal-v2.firebasestorage.app',
    measurementId: 'G-1JFDVE0RC5',
  );

}